-- Databricks notebook source
CREATE DATABASE IF NOT EXISTS config;
CREATE DATABASE IF NOT EXISTS fedw;
CREATE DATABASE IF NOT EXISTS flat_file;
CREATE DATABASE IF NOT EXISTS it_temp;
CREATE DATABASE IF NOT EXISTS s42;
CREATE DATABASE IF NOT EXISTS ve70;
CREATE DATABASE IF NOT EXISTS ve72;

-- COMMAND ----------

CREATE TABLE config.INCR_DataLoadTracking (SourceLayer String ,SourceLayerTableName String ,TargetLayer String, TargetLayerTableName String ,DatabaseName String,LastUpdatedOn String GENERATED ALWAYS AS ('1900-01-01T12:00:00.000+0000'));

-- COMMAND ----------

insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","SKA1","Consumption","GL_Account_Master","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","GL_Account_Master","Snowflake","GL_Account_Master","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Country","Snowflake","Country","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Reason_For_Cancellation","Snowflake","Reason_For_Cancellation","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","MAKT","Consumption","Material_Desc","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_Desc","Snowflake","Material_Desc","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Purchasing_Organizations","Snowflake","Purchasing_Organizations","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Release_Groups","Snowflake","Release_Groups","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Purchasing_Documents","Snowflake","Purchasing_Documents","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EINA","Consumption","Purchase_Info_Record","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EINE","Consumption","Purchase_Info_Record","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","VENDOR_QUOTE","Consumption","Purchase_Info_Record","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","VENDOR_QUOTE","Consumption","Purchase_Info_Record","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Purchase_Info_Record","Snowflake","Purchase_Info_Record","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Purchase_Info_Record_Hist","Snowflake","Purchase_Info_Record_Hist","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","UCT_VENDOR_QUOTE_HISTORY","Consumption","Purchase_Info_Record_Hist","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","UCT_VENDOR_QUOTE_HISTORY","Consumption","Purchase_Info_Record_Hist","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EIPA","Consumption","Purchase_Info_Record_Hist","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EINA","Consumption","Purchase_Info_Record_Hist","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Exchange_Rate","Snowflake","Exchange_Rate","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","TCURR","Consumption","Exchange_Rate","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Conversion_Factor","Snowflake","Conversion_Factor","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","TCURF","Consumption","Conversion_Factor","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Currency_Codes","Snowflake","Currency_Codes","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","TCURC","Consumption","Currency_Codes","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Currency_Code_Name","Snowflake","Currency_Code_Name","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","TCURT","Consumption","Currency_Code_Name","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T024D","Consumption","MRP_Controllers","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T024E","Consumption","Purchasing_Organizations","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","CURRENCY_EXCHANGE","Consumption","CURRENCY_EXCHANGE","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","CURRENCY_EXCHANGE","Consumption","CURRENCY_EXCHANGE","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","CURRENCY_EXCHANGE","Snowflake","CURRENCY_EXCHANGE","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","ADRC","Consumption","Business_Address_Services","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Business_Address_Services","Snowflake","Business_Address_Services","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T005","Consumption","Country","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T161T","Consumption","Purchase_Document_Type","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T001L","Consumption","Storage_Location","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Storage_Location","Snowflake","Storage_Location","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T460T","Consumption","Special_Procurement_Key","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T16FB","Consumption","Purchasing_Documents","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T16FG","Consumption","Release_Groups","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T023T","Consumption","Material_Group_Desc","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_Group_Desc","Snowflake","Material_Group_Desc","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T001K","Consumption","Valuation_Area","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T134","Consumption","Material_Type","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_Type","Snowflake","Material_Type","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Valuation_Area","Snowflake","Valuation_Area","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Special_Procurement_Key","Snowflake","Special_Procurement_Key","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","MRP_Controllers","Snowflake","MRP_Controllers","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Purchasing_Groups","Snowflake","Purchasing_Groups","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Purchase_Document_Type","Snowflake","Purchase_Document_Type","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T001","Consumption","Company","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","T001","Snowflake","Company","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","MARA","Consumption","Material_Global","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_Global","Snowflake","Material_Global","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","LFA1","Consumption","Supplier","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PART","Consumption","Material_Plant","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PART","Consumption","Material_Plant","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","VENDOR","Consumption","Supplier","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","VENDOR","Consumption","Supplier","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Supplier","Snowflake","Supplier","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","MARC","Consumption","Material_Plant","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_Plant","Snowflake","Material_Plant","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","MAKT","Consumption","Material_Global","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","UCT_V_AGILE_ITEM_MV","Consumption","Material_Global","IT_TEMP");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EKBE","Consumption","PO_Receipts","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","PO_Receipts","Snowflake","PO_Receipts","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","KEKO","Consumption","Part_Cost_Detail","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","CKIS","Consumption","Part_Cost_Detail","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","UCT_PART_COST_CHANGE","Consumption","Part_Cost_Detail","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","UCT_PART_COST_CHANGE","Consumption","Part_Cost_Detail","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","RECEIVER","Consumption","PO_Receipts","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","RECEIVER","Consumption","PO_Receipts","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","RECEIVER_LINE","Consumption","PO_Receipts","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","RECEIVER_LINE","Consumption","PO_Receipts","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Part_Cost_Detail","Snowflake","Part_Cost_Detail","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Company","Snowflake","Company","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EORD","Consumption","Purchase_Source_List","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PART","Consumption","Purchase_Source_List","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PART","Consumption","Purchase_Source_List","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Purchase_Source_List","Snowflake","Purchase_Source_List","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PART_UNITS_CONV","Consumption","Unit_Of_Measure","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PART_UNITS_CONV","Consumption","Unit_Of_Measure","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Unit_Of_Measure","Snowflake","Unit_Of_Measure","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","MARM","Consumption","Unit_Of_Measure","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","ACDOCA","Consumption","Accounting","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","BKPF","Consumption","Accounting","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Accounting","Snowflake","Accounting","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","ENTITY","Consumption","ENTITY","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","ENTITY","Consumption","ENTITY","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Entity","Snowflake","Entity","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EKKO","Consumption","PO_Detail","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EKPO","Consumption","PO_Detail","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PURCHASE_ORDER","Consumption","PO_Detail","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PURCHASE_ORDER","Consumption","PO_Detail","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PURC_ORDER_LINE","Consumption","PO_Detail","VE70");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","PURC_ORDER_LINE","Consumption","PO_Detail","VE72");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","PO_Detail","Snowflake","PO_Detail","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T001W","Consumption","Plant","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Plant","Snowflake","Plant","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","CommodityCode","Snowflake","CommodityCode","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","CommodityCode","Consumption","CommodityCode","FLAT_FILE");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","CEPC","Consumption","Profit_Center","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Profit_Center","Snowflake","Profit_Center","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","CEPCT","Consumption","Profit_Center_Text","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Profit_Center_Text","Snowflake","Profit_Center_Text","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T024","Consumption","Purchasing_Groups","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","ZTC2P_MAT_MAP","Consumption","Material_CPN_MPN","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_CPN_MPN","Snowflake","Material_CPN_MPN","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","ZTC2P_MAT_MAP_H","Consumption","Material_Revision_Hist","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_Revision_Hist","Snowflake","Material_Revision_Hist","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Account_Assignment_Category_Desc","Snowflake","Account_Assignment_Category_Desc","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","Material_Type_Descriptions","Snowflake","Material_Type_Descriptions","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Consumption","PO_Item_Category_Desc","Snowflake","PO_Item_Category_Desc","FEDW");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T163I","Consumption","Account_Assignment_Category_Desc","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T134T","Consumption","Material_Type_Descriptions","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","T163Y","Consumption","PO_Item_Category_Desc","S42");
insert into config.INCR_DataLoadTracking(SourceLayer,SourceLayerTableName,TargetLayer,TargetLayerTableName,DatabaseName) values("Transform","EKKN","Consumption","PO_Detail","S42");

-- COMMAND ----------


