# Databricks notebook source
from pyspark.sql.types import StructType,StructField, StringType, IntegerType, DateType, TimestampType,DoubleType
from pyspark.sql.functions import lit,current_timestamp,col, expr, when,regexp_replace,to_date
from delta.tables import *

# COMMAND ----------

consumption_table_name = 'Accounting'
write_format = 'delta'
write_path = '/mnt/uct-consumption-gen-dev/Fact/'+consumption_table_name+'/' #write_path
database_name = 'FEDW'

# COMMAND ----------

col_names_acdoca = [
    "RLDNR",
"RBUKRS",
"GJAHR",
"BELNR",
"DOCLN",
"RYEAR",
"RRCTY",
"VORGN",
"BTTYPE",
"AWTYP",
"AWORG",
"AWREF",
"AWITEM",
"AWITGRP",
"SUBTA",
"AWITEM_REV",
"SUBTA_REV",
"PREC_AWITEM",
"PREC_SUBTA",
"PREC_AWMULT",
"PREC_GJAHR",
"XSECONDARY",
"CLOSING_RUN_ID",
"SRC_AWITEM",
"SRC_AWSUBIT",
"RTCUR",
"RWCUR",
"RHCUR",
"RKCUR",
"ROCUR",
"RUNIT",
"RVUNIT",
"RRUNIT",
"RACCT",
"PRCTR",
"KOKRS",
"PPRCTR",
"LIFNR",
"KUNNR",
"TSL",
"WSL",
"WSL2",
"WSL3",
"HSL",
"KSL",
"KFSL",
"KFSL2",
"KFSL3",
"PSL",
"PSL2",
"PSL3",
"PFSL",
"PFSL2",
"PFSL3",
"CO_OSL",
"GM_OSL",
"HSLALT",
"KSLALT",
"HSLEXT",
"KSLEXT",
"HVKWRT",
"MSL",
"MFSL",
"VMSL",
"VMFSL",
"RMSL",
"CO_MEGBTR",
"CO_MEFBTR",
"HSALK3",
"KSALK3",
"HSALKV",
"KSALKV",
"HPVPRS",
"KPVPRS",
"OPVPRS",
"VPVPRS",
"HSTPRS",
"KSTPRS",
"OSTPRS",
"VSTPRS",
"HVKSAL",
"LBKUM",
"DRCRK",
"POPER",
"PERIV",
"FISCYEARPER",
"BUDAT",
"BLDAT",
"BLART",
"BUZEI",
"ZUONR",
"BSCHL",
"LINETYPE",
"KTOSL",
"SLALITTYPE",
"USNAM",
"TIMESTAMP",
"RHOART",
"GLACCOUNT_TYPE",
"KTOPL",
"REBZJ",
"REBZZ",
"RBEST",
"EBELN",
"EBELP",
"ZEKKN",
"KDPOS",
"MATNR",
"WERKS",
"KOART",
"AUGGJ",
"AFABE",
"DEPR_PERIOD",
"SETTLEMENT_RULE",
"PROZS_PN",
"KALNR",
"VPRSV",
"MLAST",
"VTSTAMP",
"MAT_KDPOS",
"MAT_PSPNR",
"BWKEY",
"HPEINH",
"KPEINH",
"OPEINH",
"VPEINH",
"MLPTYP",
"MLCATEG",
"QSBVALT",
"QSPROCESS",
"PERART",
"MLPOSNR",
"BELTP",
"MUVFLG",
"GKONT",
"GKOAR",
"PERNR",
"PAOBJNR",
"AUTYP",
"PS_PSP_PNR",
"PS_PRJ_PNR",
"SERVICE_DOC_ITEM_ID",
"SERVICE_CONTRACT_ITEM_ID",
"SOLUTION_ORDER_ITEM_ID",
"PAUTYP",
"PPS_PSP_PNR",
"PPS_PRJ_PNR",
"PKDPOS",
"PPAOBJNR",
"CO_ZLENR",
"CO_BELNR",
"CO_BUZEI",
"CO_REFBZ",
"ARBID",
"AUFPS",
"PAUFPS",
"PLANNED_PARTS_WORK",
"BDGT_CNSMPN_PERIOD",
"BDGT_CNSMPN_YEAR",
"KBLPOS",
"CBRUNID"
]

# COMMAND ----------

col_names_bkpf = [
    "RLDNR",
"BUKRS",
"GJAHR",
"BELNR",
"BUDAT",
"BLDAT",
"BLART",
"USNAM",
"MONAT",
"TCODE",
"DBBLG_GJAHR",
"STJAH",
"WAERS",
"KURSF",
"KZKRS",
"FRATH",
"GLVOR",
"AWKEY",
"HWAER",
"TXKRS",
"CTXKRS",
"PPTME",
"NUMPG",
"CASH_ALLOC",
"KURST",
"KURSX",
"GJAHR_SENDER",
"INTSUBID",
"ANXAMNT",
"ANXPERC",
"PSOTM"
]

# COMMAND ----------

df = spark.sql("select * from S42.ACDOCA where UpdatedOn > (select LastUpdatedOn from config.INCR_DataLoadTracking where SourceLayer = 'Transform' and SourceLayerTableName = 'ACDOCA' and DatabaseName = 'S42')")
df_acdoca = df.select(col_names_acdoca)
df_acdoca.createOrReplaceTempView("acdoca_tmp")
df_ts_acdoca = df.agg({"UpdatedOn": "max"}).collect()[0]
ts_acdoca = df_ts_acdoca["max(UpdatedOn)"]
print(ts_acdoca)

# COMMAND ----------

df = spark.sql("select * from S42.BKPF where UpdatedOn > (select LastUpdatedOn from config.INCR_DataLoadTracking where SourceLayer = 'Transform' and SourceLayerTableName = 'BKPF' and DatabaseName = 'S42')")
df_bkpf = df.select(col_names_bkpf)
df_bkpf.createOrReplaceTempView("bkpf_tmp")
df_ts_bkpf = df.agg({"UpdatedOn": "max"}).collect()[0]
ts_bkpf = df_ts_bkpf["max(UpdatedOn)"]
print(ts_bkpf)

# COMMAND ----------

# MAGIC %sql
# MAGIC create or replace temp view accounting
# MAGIC as
# MAGIC select 
# MAGIC ac.RLDNR as GLAccountLedger,
# MAGIC ac.RBUKRS as CompanyCode,
# MAGIC ac.GJAHR as FiscalYear,
# MAGIC ac.BELNR as AccountingDocNumber,
# MAGIC ac.DOCLN as PostingItemForLedger,
# MAGIC ac.RYEAR as GLFiscalYear,
# MAGIC ac.RRCTY as RecordType,
# MAGIC ac.VORGN as GLTransType,
# MAGIC ac.BTTYPE as BusinessTransType,
# MAGIC ac.AWTYP as ReferenceProcedure,
# MAGIC ac.AWORG as ReferenceOrgUnits,
# MAGIC ac.AWREF as ReferenceDocNumber,
# MAGIC ac.AWITEM as ReferenceDocLineItem,
# MAGIC ac.AWITGRP as GroupOfRefDocLineItems,
# MAGIC ac.SUBTA as PartialDocumentToBeBalancedToZero,
# MAGIC ac.AWITEM_REV as RefDocLineItmOfDocToBeReversed,
# MAGIC ac.SUBTA_REV as PartialDocumentToBeBalanced,
# MAGIC ac.PREC_AWITEM as PrecedingReferenceDocumentLineItem,
# MAGIC ac.PREC_SUBTA as PrecedingPartialDocToBeBalancedToZero,
# MAGIC ac.PREC_AWMULT as IdOfMultiplePrecedingDocRef,
# MAGIC ac.PREC_GJAHR as PrecedingJournalEntryFiscalYear,
# MAGIC ac.XSECONDARY as SecondaryJournalEntry,
# MAGIC ac.CLOSING_RUN_ID as UuidOfFinancialClosingRun,
# MAGIC ac.SRC_AWITEM as LineItemInSourceDocument,
# MAGIC ac.SRC_AWSUBIT as SubitemInSourceDocument,
# MAGIC ac.RTCUR as BalanceTransactionCurrency,
# MAGIC ac.RWCUR as TransactionCurrency,
# MAGIC ac.RHCUR as CompanyCodeCurrency,
# MAGIC ac.RKCUR as GlobalCurrency,
# MAGIC ac.ROCUR as FreelyDefinedCurrency1,
# MAGIC ac.RUNIT as BaseUnitOfMeasure,
# MAGIC ac.RVUNIT as UnitOfMeasureForValuationQuantity,
# MAGIC ac.RRUNIT as UnitOfMeasureForReferenceQuantity,
# MAGIC ac.RACCT as AccountNumber,
# MAGIC ac.PRCTR as ProfitCenter,
# MAGIC ac.KOKRS as ControllingArea,
# MAGIC ac.PPRCTR as PartnerProfitCenter,
# MAGIC ac.LIFNR as VendorAccountNo,
# MAGIC ac.KUNNR as CustomerNumber,
# MAGIC ac.TSL as AmountInBalanceTransactionCurrency,
# MAGIC ac.WSL as AmountInTransactionCurrency,
# MAGIC ac.WSL2 as GroupValuationAmountInTransactionCurrency,
# MAGIC ac.WSL3 as ProfitCenterValuationAmtInTransCurrency,
# MAGIC ac.HSL as AmountInCompanyCodeCurrency,
# MAGIC ac.KSL as AmountInGlobalCurrency,
# MAGIC ac.KFSL as FixedAmountInGlobalCurrency,
# MAGIC ac.KFSL2 as GroupValuationFixedAmountInGlobalCurrency,
# MAGIC ac.KFSL3 as PrctrValuationFixedAmountInGlobalCurrency,
# MAGIC ac.PSL as TotalPriceVarianceInGlobalCurrency,
# MAGIC ac.PSL2 as GroupValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC ac.PSL3 as PrctrValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC ac.PFSL as FixedPriceVarianceInGlobalCurrency,
# MAGIC ac.PFSL2 as GroupValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC ac.PFSL3 as PrctrValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC ac.CO_OSL as AmountInCoObjectCurrency,
# MAGIC ac.GM_OSL as GrantAmountInGrantCurrency,
# MAGIC ac.HSLALT as AlternativeValueInLocalCurrency,
# MAGIC ac.KSLALT as AlternativeValueInGroupCurrency,
# MAGIC ac.HSLEXT as ExternalValueInLocalCurrency,
# MAGIC ac.KSLEXT as ExternalValueInGroupCurrency,
# MAGIC ac.HVKWRT as ValueAtSalesPriceInLocalCurrency,
# MAGIC ac.MSL as Quantity,
# MAGIC ac.MFSL as FixedQuantity,
# MAGIC ac.VMSL as ValuationQuantity,
# MAGIC ac.VMFSL as FixedValuationQuantity,
# MAGIC ac.RMSL as ReferenceQuantity,
# MAGIC ac.CO_MEGBTR as CoValuationQuantity,
# MAGIC ac.CO_MEFBTR as CoValuationQuantityFix,
# MAGIC ac.HSALK3 as InventoryValueInLocalCurrency,
# MAGIC ac.KSALK3 as InventoryValueInGroupCurrency,
# MAGIC ac.HSALKV as AlternativeInventoryValueInLocalCurrency,
# MAGIC ac.KSALKV as AlternativeInventoryValueInGroupCurrency,
# MAGIC ac.HPVPRS as MovingAveragePriceInLocalCurrency,
# MAGIC ac.KPVPRS as MovingAveragePriceInGroupCurrency,
# MAGIC ac.OPVPRS as MovingAveragePriceInAnotherCurrency,
# MAGIC ac.VPVPRS as MovingAveragePriceInFourthCurrency,
# MAGIC ac.HSTPRS as StandardPriceInLocalCurrency,
# MAGIC ac.KSTPRS as StandardPriceInGroupCurrency,
# MAGIC ac.OSTPRS as StandardPriceInAnotherCurrency,
# MAGIC ac.VSTPRS as StandardPriceInFourthCurrency,
# MAGIC ac.HVKSAL as InventoryValueAtSalesPriceInLocalCurrency,
# MAGIC ac.LBKUM as InventoryQuantity,
# MAGIC ac.DRCRK as DebitCreditIndicator,
# MAGIC ac.POPER as PostingPeriod,
# MAGIC ac.PERIV as FiscalYearVariant,
# MAGIC ac.FISCYEARPER as PeriodYear,
# MAGIC ac.BUDAT as PostingDateInTheDocument,
# MAGIC ac.BLDAT as DocumentDateInDocument,
# MAGIC ac.BLART as DocumentType,
# MAGIC ac.BUZEI as NumberOfLineItemWithinAccountingDocument,
# MAGIC ac.ZUONR as AssignmentNumber,
# MAGIC ac.BSCHL as PostingKey,
# MAGIC ac.LINETYPE as ItemCategory,
# MAGIC ac.KTOSL as TransactionKey,
# MAGIC ac.SLALITTYPE as SubledgerSpecificLineItemType,
# MAGIC ac.USNAM as UserName,
# MAGIC ac.TIMESTAMP as UtcTimeStampInShortForm,
# MAGIC ac.RHOART as TypeOfOriginObject,
# MAGIC ac.GLACCOUNT_TYPE as TypeOfAGeneralLedgerAccount,
# MAGIC ac.KTOPL as ChartOfAccounts,
# MAGIC ac.REBZJ as FiscalYearOfTheRelevantInvoice,
# MAGIC ac.REBZZ as LineItemInTheRelevantInvoice,
# MAGIC ac.RBEST as CategoryOfReferencePurchaseOrder,
# MAGIC ac.EBELN as PurchasingDocument,
# MAGIC ac.EBELP as ItemNumberOfPurchasingDocument,
# MAGIC ac.ZEKKN as SequentialNumberOfAccountAssignment,
# MAGIC ac.KDPOS as ItemNumberInSalesOrder,
# MAGIC ac.MATNR as MaterialNumber,
# MAGIC ac.WERKS as Plant,
# MAGIC ac.KOART as AccountType,
# MAGIC ac.AUGGJ as FiscalYearOfClearingDocument,
# MAGIC ac.AFABE as DepreciationAreaRealOrDerived,
# MAGIC ac.DEPR_PERIOD as PostingPeriodOfDepreciation,
# MAGIC ac.SETTLEMENT_RULE as DistributionRuleGroup,
# MAGIC ac.PROZS_PN as AssetRetirementPercentageRate,
# MAGIC ac.KALNR as CostEstimateNumberForCostEstWOQtyStructure,
# MAGIC ac.VPRSV as PriceControlIndicator,
# MAGIC ac.MLAST as MaterialPriceDeterminationControl,
# MAGIC ac.VTSTAMP as ValuationTimeStamp,
# MAGIC ac.MAT_KDPOS as SalesDocuItemNumOfValuatedSpecialInventory,
# MAGIC ac.MAT_PSPNR as WbsElementOfValuatedSpecialInventory,
# MAGIC ac.BWKEY as ValuationArea,
# MAGIC ac.HPEINH as PriceUnitInLocalCurrency,
# MAGIC ac.KPEINH as PriceUnitInGroupCurrency,
# MAGIC ac.OPEINH as PriceUnitInAnotherCurrency,
# MAGIC ac.VPEINH as PriceUnitInFourthCurrency,
# MAGIC ac.MLPTYP as OriginalProcessCategory,
# MAGIC ac.MLCATEG as CategoryInMaterialUpdateStructure,
# MAGIC ac.QSBVALT as ProcurementAlternativeProcess,
# MAGIC ac.QSPROCESS as ProductionProcess,
# MAGIC ac.PERART as TypeOfPeriod,
# MAGIC ac.MLPOSNR as ItemInMaterialLedgerDocument,
# MAGIC ac.BELTP as DebitType,
# MAGIC ac.MUVFLG as IndicatorQuantityIsIncomplete,
# MAGIC ac.GKONT as OffsettingAccountNumber,
# MAGIC ac.GKOAR as OffsettingAccountType,
# MAGIC ac.PERNR as PersonnelNumber,
# MAGIC ac.PAOBJNR as ProfitabilitySegmentNumber,
# MAGIC ac.AUTYP as OrderCategory,
# MAGIC ac.PS_PSP_PNR as WbsElement,
# MAGIC ac.PS_PRJ_PNR as Project,
# MAGIC ac.SERVICE_DOC_ITEM_ID as ServiceDocumentItemId,
# MAGIC ac.SERVICE_CONTRACT_ITEM_ID as ServiceContractItemId,
# MAGIC ac.SOLUTION_ORDER_ITEM_ID as SolutionOrderItemId,
# MAGIC ac.PAUTYP as PartnerOrderCategory,
# MAGIC ac.PPS_PSP_PNR as PartnerWbsElement,
# MAGIC ac.PPS_PRJ_PNR as PartnerProject,
# MAGIC ac.PKDPOS as PartnerSalesOrderItem,
# MAGIC ac.PPAOBJNR as PartnerProfitabilitySegmentNumber,
# MAGIC ac.CO_ZLENR as DocumentItemNumber,
# MAGIC ac.CO_BELNR as DocumentNumber,
# MAGIC ac.CO_BUZEI as PostingRow,
# MAGIC ac.CO_REFBZ as PostingRowOfReferenceDocument,
# MAGIC ac.ARBID as ObjectIdOfTheResource,
# MAGIC ac.AUFPS as OrderItemNumber,
# MAGIC ac.PAUFPS as PartnerOrderItemNumber,
# MAGIC ac.PLANNED_PARTS_WORK as PlannedPartsWork,
# MAGIC ac.BDGT_CNSMPN_PERIOD as CcFiscalPeriodForBudgetConsumptionDate,
# MAGIC ac.BDGT_CNSMPN_YEAR as CcFiscalYearForBudgetConsumptionDate,
# MAGIC ac.KBLPOS as EarmarkedFundsDocumentItem,
# MAGIC ac.CBRUNID as CutbackRunId,
# MAGIC bk.MONAT as FiscalPeriod,
# MAGIC bk.TCODE as TransactionCode,
# MAGIC bk.DBBLG_GJAHR as RecurringEntryDocumentFiscalYear,
# MAGIC bk.STJAH as FiscalYearOfReversalDocument,
# MAGIC bk.WAERS as CurrencyKey,
# MAGIC bk.KURSF as ExchangeRate,
# MAGIC bk.KZKRS as GroupCurrencyExchangeRate,
# MAGIC bk.FRATH as UnplannedDeliveryCosts,
# MAGIC bk.GLVOR as BusinessTransaction,
# MAGIC bk.AWKEY as ObjectKey,
# MAGIC bk.HWAER as LocalCurrency,
# MAGIC bk.TXKRS as ExchangeRateForTaxes,
# MAGIC bk.CTXKRS as RateForTaxValuesInCountryCurrency,
# MAGIC bk.PPTME as TimeOfParking,
# MAGIC bk.NUMPG as NumberOfPagesOfInvoice,
# MAGIC bk.CASH_ALLOC as CashRelevantDocument,
# MAGIC bk.KURST as ExchangeRateType,
# MAGIC bk.KURSX as MarketDataExchangeRate,
# MAGIC bk.GJAHR_SENDER as FiscYearOfAnAccDocInTheSenderSystem,
# MAGIC bk.INTSUBID as InternallyAssignedSubidForAwkey,
# MAGIC bk.ANXAMNT as AnnexationAmount,
# MAGIC bk.ANXPERC as AnnexationPercentage,
# MAGIC bk.PSOTM as LastChangedAt,
# MAGIC 'SAP' as DataSource,
# MAGIC now() as UpdatedOn
# MAGIC from 
# MAGIC S42.ACDOCA as ac
# MAGIC left join 
# MAGIC S42.BKPF as bk
# MAGIC on 
# MAGIC --ac.RLDNR = bk.RLDNR
# MAGIC ac.RBUKRS = bk.BUKRS
# MAGIC and ac.GJAHR = bk.GJAHR
# MAGIC and ac.BELNR = bk.BELNR

# COMMAND ----------

df_accounting = spark.sql("select * from accounting")

# COMMAND ----------

if(DeltaTable.isDeltaTable(spark, write_path) == False): 
        df_accounting.write.format(write_format).mode("overwrite").save(write_path) 
        spark.sql("CREATE TABLE IF NOT EXISTS " +database_name+"."+ consumption_table_name + " USING DELTA LOCATION '" + write_path + "'")

# COMMAND ----------

df_accounting.createOrReplaceTempView('tmp_accounting')

# COMMAND ----------

# MAGIC %sql 
# MAGIC Merge into fedw.accounting as T
# MAGIC Using (select * from tmp_accounting where CompanyCode != '0') as S
# MAGIC on T.GLAccountLedger = S.GLAccountLedger and 
# MAGIC T.CompanyCode = S.CompanyCode and 
# MAGIC T.FiscalYear = S.FiscalYear and
# MAGIC T.AccountingDocNumber = S.AccountingDocNumber and
# MAGIC T.PostingItemForLedger = S.PostingItemForLedger
# MAGIC WHEN MATCHED THEN 
# MAGIC UPDATE SET
# MAGIC T.GLAccountLedger = S.GLAccountLedger,
# MAGIC T.CompanyCode = S.CompanyCode,
# MAGIC T.FiscalYear = S.FiscalYear,
# MAGIC T.AccountingDocNumber = S.AccountingDocNumber,
# MAGIC T.PostingItemForLedger = S.PostingItemForLedger,
# MAGIC T.GLFiscalYear = S.GLFiscalYear,
# MAGIC T.RecordType = S.RecordType,
# MAGIC T.GLTransType = S.GLTransType,
# MAGIC T.BusinessTransType = S.BusinessTransType,
# MAGIC T.ReferenceProcedure = S.ReferenceProcedure,
# MAGIC T.ReferenceOrgUnits = S.ReferenceOrgUnits,
# MAGIC T.ReferenceDocNumber = S.ReferenceDocNumber,
# MAGIC T.ReferenceDocLineItem = S.ReferenceDocLineItem,
# MAGIC T.GroupOfRefDocLineItems = S.GroupOfRefDocLineItems,
# MAGIC T.PartialDocumentToBeBalancedToZero = S.PartialDocumentToBeBalancedToZero,
# MAGIC T.RefDocLineItmOfDocToBeReversed = S.RefDocLineItmOfDocToBeReversed,
# MAGIC T.PartialDocumentToBeBalanced = S.PartialDocumentToBeBalanced,
# MAGIC T.PrecedingReferenceDocumentLineItem = S.PrecedingReferenceDocumentLineItem,
# MAGIC T.PrecedingPartialDocToBeBalancedToZero = S.PrecedingPartialDocToBeBalancedToZero,
# MAGIC T.IdOfMultiplePrecedingDocRef = S.IdOfMultiplePrecedingDocRef,
# MAGIC T.PrecedingJournalEntryFiscalYear = S.PrecedingJournalEntryFiscalYear,
# MAGIC T.SecondaryJournalEntry = S.SecondaryJournalEntry,
# MAGIC T.UuidOfFinancialClosingRun = S.UuidOfFinancialClosingRun,
# MAGIC T.LineItemInSourceDocument = S.LineItemInSourceDocument,
# MAGIC T.SubitemInSourceDocument = S.SubitemInSourceDocument,
# MAGIC T.BalanceTransactionCurrency = S.BalanceTransactionCurrency,
# MAGIC T.TransactionCurrency = S.TransactionCurrency,
# MAGIC T.CompanyCodeCurrency = S.CompanyCodeCurrency,
# MAGIC T.GlobalCurrency = S.GlobalCurrency,
# MAGIC T.FreelyDefinedCurrency1 = S.FreelyDefinedCurrency1,
# MAGIC T.BaseUnitOfMeasure = S.BaseUnitOfMeasure,
# MAGIC T.UnitOfMeasureForValuationQuantity = S.UnitOfMeasureForValuationQuantity,
# MAGIC T.UnitOfMeasureForReferenceQuantity = S.UnitOfMeasureForReferenceQuantity,
# MAGIC T.AccountNumber = S.AccountNumber,
# MAGIC T.ProfitCenter = S.ProfitCenter,
# MAGIC T.ControllingArea = S.ControllingArea,
# MAGIC T.PartnerProfitCenter = S.PartnerProfitCenter,
# MAGIC T.VendorAccountNo = S.VendorAccountNo,
# MAGIC T.CustomerNumber = S.CustomerNumber,
# MAGIC T.AmountInBalanceTransactionCurrency = S.AmountInBalanceTransactionCurrency,
# MAGIC T.AmountInTransactionCurrency = S.AmountInTransactionCurrency,
# MAGIC T.GroupValuationAmountInTransactionCurrency = S.GroupValuationAmountInTransactionCurrency,
# MAGIC T.ProfitCenterValuationAmtInTransCurrency = S.ProfitCenterValuationAmtInTransCurrency,
# MAGIC T.AmountInCompanyCodeCurrency = S.AmountInCompanyCodeCurrency,
# MAGIC T.AmountInGlobalCurrency = S.AmountInGlobalCurrency,
# MAGIC T.FixedAmountInGlobalCurrency = S.FixedAmountInGlobalCurrency,
# MAGIC T.GroupValuationFixedAmountInGlobalCurrency = S.GroupValuationFixedAmountInGlobalCurrency,
# MAGIC T.PrctrValuationFixedAmountInGlobalCurrency = S.PrctrValuationFixedAmountInGlobalCurrency,
# MAGIC T.TotalPriceVarianceInGlobalCurrency = S.TotalPriceVarianceInGlobalCurrency,
# MAGIC T.GroupValuationTotalPriceVarianceInGlobalCurrency = S.GroupValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC T.PrctrValuationTotalPriceVarianceInGlobalCurrency = S.PrctrValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC T.FixedPriceVarianceInGlobalCurrency = S.FixedPriceVarianceInGlobalCurrency,
# MAGIC T.GroupValuationFixedPriceVarianceInGlobalCurrency = S.GroupValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC T.PrctrValuationFixedPriceVarianceInGlobalCurrency = S.PrctrValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC T.AmountInCoObjectCurrency = S.AmountInCoObjectCurrency,
# MAGIC T.GrantAmountInGrantCurrency = S.GrantAmountInGrantCurrency,
# MAGIC T.AlternativeValueInLocalCurrency = S.AlternativeValueInLocalCurrency,
# MAGIC T.AlternativeValueInGroupCurrency = S.AlternativeValueInGroupCurrency,
# MAGIC T.ExternalValueInLocalCurrency = S.ExternalValueInLocalCurrency,
# MAGIC T.ExternalValueInGroupCurrency = S.ExternalValueInGroupCurrency,
# MAGIC T.ValueAtSalesPriceInLocalCurrency = S.ValueAtSalesPriceInLocalCurrency,
# MAGIC T.Quantity = S.Quantity,
# MAGIC T.FixedQuantity = S.FixedQuantity,
# MAGIC T.ValuationQuantity = S.ValuationQuantity,
# MAGIC T.FixedValuationQuantity = S.FixedValuationQuantity,
# MAGIC T.ReferenceQuantity = S.ReferenceQuantity,
# MAGIC T.CoValuationQuantity = S.CoValuationQuantity,
# MAGIC T.CoValuationQuantityFix = S.CoValuationQuantityFix,
# MAGIC T.InventoryValueInLocalCurrency = S.InventoryValueInLocalCurrency,
# MAGIC T.InventoryValueInGroupCurrency = S.InventoryValueInGroupCurrency,
# MAGIC T.AlternativeInventoryValueInLocalCurrency = S.AlternativeInventoryValueInLocalCurrency,
# MAGIC T.AlternativeInventoryValueInGroupCurrency = S.AlternativeInventoryValueInGroupCurrency,
# MAGIC T.MovingAveragePriceInLocalCurrency = S.MovingAveragePriceInLocalCurrency,
# MAGIC T.MovingAveragePriceInGroupCurrency = S.MovingAveragePriceInGroupCurrency,
# MAGIC T.MovingAveragePriceInAnotherCurrency = S.MovingAveragePriceInAnotherCurrency,
# MAGIC T.MovingAveragePriceInFourthCurrency = S.MovingAveragePriceInFourthCurrency,
# MAGIC T.StandardPriceInLocalCurrency = S.StandardPriceInLocalCurrency,
# MAGIC T.StandardPriceInGroupCurrency = S.StandardPriceInGroupCurrency,
# MAGIC T.StandardPriceInAnotherCurrency = S.StandardPriceInAnotherCurrency,
# MAGIC T.StandardPriceInFourthCurrency = S.StandardPriceInFourthCurrency,
# MAGIC T.InventoryValueAtSalesPriceInLocalCurrency = S.InventoryValueAtSalesPriceInLocalCurrency,
# MAGIC T.InventoryQuantity = S.InventoryQuantity,
# MAGIC T.DebitCreditIndicator = S.DebitCreditIndicator,
# MAGIC T.PostingPeriod = S.PostingPeriod,
# MAGIC T.FiscalYearVariant = S.FiscalYearVariant,
# MAGIC T.PeriodYear = S.PeriodYear,
# MAGIC T.PostingDateInTheDocument = S.PostingDateInTheDocument,
# MAGIC T.DocumentDateInDocument = S.DocumentDateInDocument,
# MAGIC T.DocumentType = S.DocumentType,
# MAGIC T.NumberOfLineItemWithinAccountingDocument = S.NumberOfLineItemWithinAccountingDocument,
# MAGIC T.AssignmentNumber = S.AssignmentNumber,
# MAGIC T.PostingKey = S.PostingKey,
# MAGIC T.ItemCategory = S.ItemCategory,
# MAGIC T.TransactionKey = S.TransactionKey,
# MAGIC T.SubledgerSpecificLineItemType = S.SubledgerSpecificLineItemType,
# MAGIC T.UserName = S.UserName,
# MAGIC T.UtcTimeStampInShortForm = S.UtcTimeStampInShortForm,
# MAGIC T.TypeOfOriginObject = S.TypeOfOriginObject,
# MAGIC T.TypeOfAGeneralLedgerAccount = S.TypeOfAGeneralLedgerAccount,
# MAGIC T.ChartOfAccounts = S.ChartOfAccounts,
# MAGIC T.FiscalYearOfTheRelevantInvoice = S.FiscalYearOfTheRelevantInvoice,
# MAGIC T.LineItemInTheRelevantInvoice = S.LineItemInTheRelevantInvoice,
# MAGIC T.CategoryOfReferencePurchaseOrder = S.CategoryOfReferencePurchaseOrder,
# MAGIC T.PurchasingDocument = S.PurchasingDocument,
# MAGIC T.ItemNumberOfPurchasingDocument = S.ItemNumberOfPurchasingDocument,
# MAGIC T.SequentialNumberOfAccountAssignment = S.SequentialNumberOfAccountAssignment,
# MAGIC T.ItemNumberInSalesOrder = S.ItemNumberInSalesOrder,
# MAGIC T.MaterialNumber = S.MaterialNumber,
# MAGIC T.Plant = S.Plant,
# MAGIC T.AccountType = S.AccountType,
# MAGIC T.FiscalYearOfClearingDocument = S.FiscalYearOfClearingDocument,
# MAGIC T.DepreciationAreaRealOrDerived = S.DepreciationAreaRealOrDerived,
# MAGIC T.PostingPeriodOfDepreciation = S.PostingPeriodOfDepreciation,
# MAGIC T.DistributionRuleGroup = S.DistributionRuleGroup,
# MAGIC T.AssetRetirementPercentageRate = S.AssetRetirementPercentageRate,
# MAGIC T.CostEstimateNumberForCostEstWOQtyStructure = S.CostEstimateNumberForCostEstWOQtyStructure,
# MAGIC T.PriceControlIndicator = S.PriceControlIndicator,
# MAGIC T.MaterialPriceDeterminationControl = S.MaterialPriceDeterminationControl,
# MAGIC T.ValuationTimeStamp = S.ValuationTimeStamp,
# MAGIC T.SalesDocuItemNumOfValuatedSpecialInventory = S.SalesDocuItemNumOfValuatedSpecialInventory,
# MAGIC T.WbsElementOfValuatedSpecialInventory = S.WbsElementOfValuatedSpecialInventory,
# MAGIC T.ValuationArea = S.ValuationArea,
# MAGIC T.PriceUnitInLocalCurrency = S.PriceUnitInLocalCurrency,
# MAGIC T.PriceUnitInGroupCurrency = S.PriceUnitInGroupCurrency,
# MAGIC T.PriceUnitInAnotherCurrency = S.PriceUnitInAnotherCurrency,
# MAGIC T.PriceUnitInFourthCurrency = S.PriceUnitInFourthCurrency,
# MAGIC T.OriginalProcessCategory = S.OriginalProcessCategory,
# MAGIC T.CategoryInMaterialUpdateStructure = S.CategoryInMaterialUpdateStructure,
# MAGIC T.ProcurementAlternativeProcess = S.ProcurementAlternativeProcess,
# MAGIC T.ProductionProcess = S.ProductionProcess,
# MAGIC T.TypeOfPeriod = S.TypeOfPeriod,
# MAGIC T.ItemInMaterialLedgerDocument = S.ItemInMaterialLedgerDocument,
# MAGIC T.DebitType = S.DebitType,
# MAGIC T.IndicatorQuantityIsIncomplete = S.IndicatorQuantityIsIncomplete,
# MAGIC T.OffsettingAccountNumber = S.OffsettingAccountNumber,
# MAGIC T.OffsettingAccountType = S.OffsettingAccountType,
# MAGIC T.PersonnelNumber = S.PersonnelNumber,
# MAGIC T.ProfitabilitySegmentNumber = S.ProfitabilitySegmentNumber,
# MAGIC T.OrderCategory = S.OrderCategory,
# MAGIC T.WbsElement = S.WbsElement,
# MAGIC T.Project = S.Project,
# MAGIC T.ServiceDocumentItemId = S.ServiceDocumentItemId,
# MAGIC T.ServiceContractItemId = S.ServiceContractItemId,
# MAGIC T.SolutionOrderItemId = S.SolutionOrderItemId,
# MAGIC T.PartnerOrderCategory = S.PartnerOrderCategory,
# MAGIC T.PartnerWbsElement = S.PartnerWbsElement,
# MAGIC T.PartnerProject = S.PartnerProject,
# MAGIC T.PartnerSalesOrderItem = S.PartnerSalesOrderItem,
# MAGIC T.PartnerProfitabilitySegmentNumber = S.PartnerProfitabilitySegmentNumber,
# MAGIC T.DocumentItemNumber = S.DocumentItemNumber,
# MAGIC T.DocumentNumber = S.DocumentNumber,
# MAGIC T.PostingRow = S.PostingRow,
# MAGIC T.PostingRowOfReferenceDocument = S.PostingRowOfReferenceDocument,
# MAGIC T.ObjectIdOfTheResource = S.ObjectIdOfTheResource,
# MAGIC T.OrderItemNumber = S.OrderItemNumber,
# MAGIC T.PartnerOrderItemNumber = S.PartnerOrderItemNumber,
# MAGIC T.PlannedPartsWork = S.PlannedPartsWork,
# MAGIC T.CcFiscalPeriodForBudgetConsumptionDate = S.CcFiscalPeriodForBudgetConsumptionDate,
# MAGIC T.CcFiscalYearForBudgetConsumptionDate = S.CcFiscalYearForBudgetConsumptionDate,
# MAGIC T.EarmarkedFundsDocumentItem = S.EarmarkedFundsDocumentItem,
# MAGIC T.CutbackRunId = S.CutbackRunId,
# MAGIC T.FiscalPeriod = S.FiscalPeriod,
# MAGIC T.TransactionCode = S.TransactionCode,
# MAGIC T.RecurringEntryDocumentFiscalYear = S.RecurringEntryDocumentFiscalYear,
# MAGIC T.FiscalYearOfReversalDocument = S.FiscalYearOfReversalDocument,
# MAGIC T.CurrencyKey = S.CurrencyKey,
# MAGIC T.ExchangeRate = S.ExchangeRate,
# MAGIC T.GroupCurrencyExchangeRate = S.GroupCurrencyExchangeRate,
# MAGIC T.UnplannedDeliveryCosts = S.UnplannedDeliveryCosts,
# MAGIC T.BusinessTransaction = S.BusinessTransaction,
# MAGIC T.ObjectKey = S.ObjectKey,
# MAGIC T.LocalCurrency = S.LocalCurrency,
# MAGIC T.ExchangeRateForTaxes = S.ExchangeRateForTaxes,
# MAGIC T.RateForTaxValuesInCountryCurrency = S.RateForTaxValuesInCountryCurrency,
# MAGIC T.TimeOfParking = S.TimeOfParking,
# MAGIC T.NumberOfPagesOfInvoice = S.NumberOfPagesOfInvoice,
# MAGIC T.CashRelevantDocument = S.CashRelevantDocument,
# MAGIC T.ExchangeRateType = S.ExchangeRateType,
# MAGIC T.MarketDataExchangeRate = S.MarketDataExchangeRate,
# MAGIC T.FiscYearOfAnAccDocInTheSenderSystem = S.FiscYearOfAnAccDocInTheSenderSystem,
# MAGIC T.InternallyAssignedSubidForAwkey = S.InternallyAssignedSubidForAwkey,
# MAGIC T.AnnexationAmount = S.AnnexationAmount,
# MAGIC T.AnnexationPercentage = S.AnnexationPercentage,
# MAGIC T.LastChangedAt = S.LastChangedAt,
# MAGIC T.DataSource = S.DataSource,
# MAGIC T.UpdatedOn = now()
# MAGIC WHEN NOT MATCHED
# MAGIC     THEN INSERT
# MAGIC (
# MAGIC GLAccountLedger,
# MAGIC CompanyCode,
# MAGIC FiscalYear,
# MAGIC AccountingDocNumber,
# MAGIC PostingItemForLedger,
# MAGIC GLFiscalYear,
# MAGIC RecordType,
# MAGIC GLTransType,
# MAGIC BusinessTransType,
# MAGIC ReferenceProcedure,
# MAGIC ReferenceOrgUnits,
# MAGIC ReferenceDocNumber,
# MAGIC ReferenceDocLineItem,
# MAGIC GroupOfRefDocLineItems,
# MAGIC PartialDocumentToBeBalancedToZero,
# MAGIC RefDocLineItmOfDocToBeReversed,
# MAGIC PartialDocumentToBeBalanced,
# MAGIC PrecedingReferenceDocumentLineItem,
# MAGIC PrecedingPartialDocToBeBalancedToZero,
# MAGIC IdOfMultiplePrecedingDocRef,
# MAGIC PrecedingJournalEntryFiscalYear,
# MAGIC SecondaryJournalEntry,
# MAGIC UuidOfFinancialClosingRun,
# MAGIC LineItemInSourceDocument,
# MAGIC SubitemInSourceDocument,
# MAGIC BalanceTransactionCurrency,
# MAGIC TransactionCurrency,
# MAGIC CompanyCodeCurrency,
# MAGIC GlobalCurrency,
# MAGIC FreelyDefinedCurrency1,
# MAGIC BaseUnitOfMeasure,
# MAGIC UnitOfMeasureForValuationQuantity,
# MAGIC UnitOfMeasureForReferenceQuantity,
# MAGIC AccountNumber,
# MAGIC ProfitCenter,
# MAGIC ControllingArea,
# MAGIC PartnerProfitCenter,
# MAGIC VendorAccountNo,
# MAGIC CustomerNumber,
# MAGIC AmountInBalanceTransactionCurrency,
# MAGIC AmountInTransactionCurrency,
# MAGIC GroupValuationAmountInTransactionCurrency,
# MAGIC ProfitCenterValuationAmtInTransCurrency,
# MAGIC AmountInCompanyCodeCurrency,
# MAGIC AmountInGlobalCurrency,
# MAGIC FixedAmountInGlobalCurrency,
# MAGIC GroupValuationFixedAmountInGlobalCurrency,
# MAGIC PrctrValuationFixedAmountInGlobalCurrency,
# MAGIC TotalPriceVarianceInGlobalCurrency,
# MAGIC GroupValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC PrctrValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC FixedPriceVarianceInGlobalCurrency,
# MAGIC GroupValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC PrctrValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC AmountInCoObjectCurrency,
# MAGIC GrantAmountInGrantCurrency,
# MAGIC AlternativeValueInLocalCurrency,
# MAGIC AlternativeValueInGroupCurrency,
# MAGIC ExternalValueInLocalCurrency,
# MAGIC ExternalValueInGroupCurrency,
# MAGIC ValueAtSalesPriceInLocalCurrency,
# MAGIC Quantity,
# MAGIC FixedQuantity,
# MAGIC ValuationQuantity,
# MAGIC FixedValuationQuantity,
# MAGIC ReferenceQuantity,
# MAGIC CoValuationQuantity,
# MAGIC CoValuationQuantityFix,
# MAGIC InventoryValueInLocalCurrency,
# MAGIC InventoryValueInGroupCurrency,
# MAGIC AlternativeInventoryValueInLocalCurrency,
# MAGIC AlternativeInventoryValueInGroupCurrency,
# MAGIC MovingAveragePriceInLocalCurrency,
# MAGIC MovingAveragePriceInGroupCurrency,
# MAGIC MovingAveragePriceInAnotherCurrency,
# MAGIC MovingAveragePriceInFourthCurrency,
# MAGIC StandardPriceInLocalCurrency,
# MAGIC StandardPriceInGroupCurrency,
# MAGIC StandardPriceInAnotherCurrency,
# MAGIC StandardPriceInFourthCurrency,
# MAGIC InventoryValueAtSalesPriceInLocalCurrency,
# MAGIC InventoryQuantity,
# MAGIC DebitCreditIndicator,
# MAGIC PostingPeriod,
# MAGIC FiscalYearVariant,
# MAGIC PeriodYear,
# MAGIC PostingDateInTheDocument,
# MAGIC DocumentDateInDocument,
# MAGIC DocumentType,
# MAGIC NumberOfLineItemWithinAccountingDocument,
# MAGIC AssignmentNumber,
# MAGIC PostingKey,
# MAGIC ItemCategory,
# MAGIC TransactionKey,
# MAGIC SubledgerSpecificLineItemType,
# MAGIC UserName,
# MAGIC UtcTimeStampInShortForm,
# MAGIC TypeOfOriginObject,
# MAGIC TypeOfAGeneralLedgerAccount,
# MAGIC ChartOfAccounts,
# MAGIC FiscalYearOfTheRelevantInvoice,
# MAGIC LineItemInTheRelevantInvoice,
# MAGIC CategoryOfReferencePurchaseOrder,
# MAGIC PurchasingDocument,
# MAGIC ItemNumberOfPurchasingDocument,
# MAGIC SequentialNumberOfAccountAssignment,
# MAGIC ItemNumberInSalesOrder,
# MAGIC MaterialNumber,
# MAGIC Plant,
# MAGIC AccountType,
# MAGIC FiscalYearOfClearingDocument,
# MAGIC DepreciationAreaRealOrDerived,
# MAGIC PostingPeriodOfDepreciation,
# MAGIC DistributionRuleGroup,
# MAGIC AssetRetirementPercentageRate,
# MAGIC CostEstimateNumberForCostEstWOQtyStructure,
# MAGIC PriceControlIndicator,
# MAGIC MaterialPriceDeterminationControl,
# MAGIC ValuationTimeStamp,
# MAGIC SalesDocuItemNumOfValuatedSpecialInventory,
# MAGIC WbsElementOfValuatedSpecialInventory,
# MAGIC ValuationArea,
# MAGIC PriceUnitInLocalCurrency,
# MAGIC PriceUnitInGroupCurrency,
# MAGIC PriceUnitInAnotherCurrency,
# MAGIC PriceUnitInFourthCurrency,
# MAGIC OriginalProcessCategory,
# MAGIC CategoryInMaterialUpdateStructure,
# MAGIC ProcurementAlternativeProcess,
# MAGIC ProductionProcess,
# MAGIC TypeOfPeriod,
# MAGIC ItemInMaterialLedgerDocument,
# MAGIC DebitType,
# MAGIC IndicatorQuantityIsIncomplete,
# MAGIC OffsettingAccountNumber,
# MAGIC OffsettingAccountType,
# MAGIC PersonnelNumber,
# MAGIC ProfitabilitySegmentNumber,
# MAGIC OrderCategory,
# MAGIC WbsElement,
# MAGIC Project,
# MAGIC ServiceDocumentItemId,
# MAGIC ServiceContractItemId,
# MAGIC SolutionOrderItemId,
# MAGIC PartnerOrderCategory,
# MAGIC PartnerWbsElement,
# MAGIC PartnerProject,
# MAGIC PartnerSalesOrderItem,
# MAGIC PartnerProfitabilitySegmentNumber,
# MAGIC DocumentItemNumber,
# MAGIC DocumentNumber,
# MAGIC PostingRow,
# MAGIC PostingRowOfReferenceDocument,
# MAGIC ObjectIdOfTheResource,
# MAGIC OrderItemNumber,
# MAGIC PartnerOrderItemNumber,
# MAGIC PlannedPartsWork,
# MAGIC CcFiscalPeriodForBudgetConsumptionDate,
# MAGIC CcFiscalYearForBudgetConsumptionDate,
# MAGIC EarmarkedFundsDocumentItem,
# MAGIC CutbackRunId,
# MAGIC FiscalPeriod,
# MAGIC TransactionCode,
# MAGIC RecurringEntryDocumentFiscalYear,
# MAGIC FiscalYearOfReversalDocument,
# MAGIC CurrencyKey,
# MAGIC ExchangeRate,
# MAGIC GroupCurrencyExchangeRate,
# MAGIC UnplannedDeliveryCosts,
# MAGIC BusinessTransaction,
# MAGIC ObjectKey,
# MAGIC LocalCurrency,
# MAGIC ExchangeRateForTaxes,
# MAGIC RateForTaxValuesInCountryCurrency,
# MAGIC TimeOfParking,
# MAGIC NumberOfPagesOfInvoice,
# MAGIC CashRelevantDocument,
# MAGIC ExchangeRateType,
# MAGIC MarketDataExchangeRate,
# MAGIC FiscYearOfAnAccDocInTheSenderSystem,
# MAGIC InternallyAssignedSubidForAwkey,
# MAGIC AnnexationAmount,
# MAGIC AnnexationPercentage,
# MAGIC LastChangedAt,
# MAGIC DataSource,
# MAGIC UpdatedOn
# MAGIC )
# MAGIC values
# MAGIC (
# MAGIC S.GLAccountLedger,
# MAGIC S.CompanyCode,
# MAGIC S.FiscalYear,
# MAGIC S.AccountingDocNumber,
# MAGIC S.PostingItemForLedger,
# MAGIC S.GLFiscalYear,
# MAGIC S.RecordType,
# MAGIC S.GLTransType,
# MAGIC S.BusinessTransType,
# MAGIC S.ReferenceProcedure,
# MAGIC S.ReferenceOrgUnits,
# MAGIC S.ReferenceDocNumber,
# MAGIC S.ReferenceDocLineItem,
# MAGIC S.GroupOfRefDocLineItems,
# MAGIC S.PartialDocumentToBeBalancedToZero,
# MAGIC S.RefDocLineItmOfDocToBeReversed,
# MAGIC S.PartialDocumentToBeBalanced,
# MAGIC S.PrecedingReferenceDocumentLineItem,
# MAGIC S.PrecedingPartialDocToBeBalancedToZero,
# MAGIC S.IdOfMultiplePrecedingDocRef,
# MAGIC S.PrecedingJournalEntryFiscalYear,
# MAGIC S.SecondaryJournalEntry,
# MAGIC S.UuidOfFinancialClosingRun,
# MAGIC S.LineItemInSourceDocument,
# MAGIC S.SubitemInSourceDocument,
# MAGIC S.BalanceTransactionCurrency,
# MAGIC S.TransactionCurrency,
# MAGIC S.CompanyCodeCurrency,
# MAGIC S.GlobalCurrency,
# MAGIC S.FreelyDefinedCurrency1,
# MAGIC S.BaseUnitOfMeasure,
# MAGIC S.UnitOfMeasureForValuationQuantity,
# MAGIC S.UnitOfMeasureForReferenceQuantity,
# MAGIC S.AccountNumber,
# MAGIC S.ProfitCenter,
# MAGIC S.ControllingArea,
# MAGIC S.PartnerProfitCenter,
# MAGIC S.VendorAccountNo,
# MAGIC S.CustomerNumber,
# MAGIC S.AmountInBalanceTransactionCurrency,
# MAGIC S.AmountInTransactionCurrency,
# MAGIC S.GroupValuationAmountInTransactionCurrency,
# MAGIC S.ProfitCenterValuationAmtInTransCurrency,
# MAGIC S.AmountInCompanyCodeCurrency,
# MAGIC S.AmountInGlobalCurrency,
# MAGIC S.FixedAmountInGlobalCurrency,
# MAGIC S.GroupValuationFixedAmountInGlobalCurrency,
# MAGIC S.PrctrValuationFixedAmountInGlobalCurrency,
# MAGIC S.TotalPriceVarianceInGlobalCurrency,
# MAGIC S.GroupValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC S.PrctrValuationTotalPriceVarianceInGlobalCurrency,
# MAGIC S.FixedPriceVarianceInGlobalCurrency,
# MAGIC S.GroupValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC S.PrctrValuationFixedPriceVarianceInGlobalCurrency,
# MAGIC S.AmountInCoObjectCurrency,
# MAGIC S.GrantAmountInGrantCurrency,
# MAGIC S.AlternativeValueInLocalCurrency,
# MAGIC S.AlternativeValueInGroupCurrency,
# MAGIC S.ExternalValueInLocalCurrency,
# MAGIC S.ExternalValueInGroupCurrency,
# MAGIC S.ValueAtSalesPriceInLocalCurrency,
# MAGIC S.Quantity,
# MAGIC S.FixedQuantity,
# MAGIC S.ValuationQuantity,
# MAGIC S.FixedValuationQuantity,
# MAGIC S.ReferenceQuantity,
# MAGIC S.CoValuationQuantity,
# MAGIC S.CoValuationQuantityFix,
# MAGIC S.InventoryValueInLocalCurrency,
# MAGIC S.InventoryValueInGroupCurrency,
# MAGIC S.AlternativeInventoryValueInLocalCurrency,
# MAGIC S.AlternativeInventoryValueInGroupCurrency,
# MAGIC S.MovingAveragePriceInLocalCurrency,
# MAGIC S.MovingAveragePriceInGroupCurrency,
# MAGIC S.MovingAveragePriceInAnotherCurrency,
# MAGIC S.MovingAveragePriceInFourthCurrency,
# MAGIC S.StandardPriceInLocalCurrency,
# MAGIC S.StandardPriceInGroupCurrency,
# MAGIC S.StandardPriceInAnotherCurrency,
# MAGIC S.StandardPriceInFourthCurrency,
# MAGIC S.InventoryValueAtSalesPriceInLocalCurrency,
# MAGIC S.InventoryQuantity,
# MAGIC S.DebitCreditIndicator,
# MAGIC S.PostingPeriod,
# MAGIC S.FiscalYearVariant,
# MAGIC S.PeriodYear,
# MAGIC S.PostingDateInTheDocument,
# MAGIC S.DocumentDateInDocument,
# MAGIC S.DocumentType,
# MAGIC S.NumberOfLineItemWithinAccountingDocument,
# MAGIC S.AssignmentNumber,
# MAGIC S.PostingKey,
# MAGIC S.ItemCategory,
# MAGIC S.TransactionKey,
# MAGIC S.SubledgerSpecificLineItemType,
# MAGIC S.UserName,
# MAGIC S.UtcTimeStampInShortForm,
# MAGIC S.TypeOfOriginObject,
# MAGIC S.TypeOfAGeneralLedgerAccount,
# MAGIC S.ChartOfAccounts,
# MAGIC S.FiscalYearOfTheRelevantInvoice,
# MAGIC S.LineItemInTheRelevantInvoice,
# MAGIC S.CategoryOfReferencePurchaseOrder,
# MAGIC S.PurchasingDocument,
# MAGIC S.ItemNumberOfPurchasingDocument,
# MAGIC S.SequentialNumberOfAccountAssignment,
# MAGIC S.ItemNumberInSalesOrder,
# MAGIC S.MaterialNumber,
# MAGIC S.Plant,
# MAGIC S.AccountType,
# MAGIC S.FiscalYearOfClearingDocument,
# MAGIC S.DepreciationAreaRealOrDerived,
# MAGIC S.PostingPeriodOfDepreciation,
# MAGIC S.DistributionRuleGroup,
# MAGIC S.AssetRetirementPercentageRate,
# MAGIC S.CostEstimateNumberForCostEstWOQtyStructure,
# MAGIC S.PriceControlIndicator,
# MAGIC S.MaterialPriceDeterminationControl,
# MAGIC S.ValuationTimeStamp,
# MAGIC S.SalesDocuItemNumOfValuatedSpecialInventory,
# MAGIC S.WbsElementOfValuatedSpecialInventory,
# MAGIC S.ValuationArea,
# MAGIC S.PriceUnitInLocalCurrency,
# MAGIC S.PriceUnitInGroupCurrency,
# MAGIC S.PriceUnitInAnotherCurrency,
# MAGIC S.PriceUnitInFourthCurrency,
# MAGIC S.OriginalProcessCategory,
# MAGIC S.CategoryInMaterialUpdateStructure,
# MAGIC S.ProcurementAlternativeProcess,
# MAGIC S.ProductionProcess,
# MAGIC S.TypeOfPeriod,
# MAGIC S.ItemInMaterialLedgerDocument,
# MAGIC S.DebitType,
# MAGIC S.IndicatorQuantityIsIncomplete,
# MAGIC S.OffsettingAccountNumber,
# MAGIC S.OffsettingAccountType,
# MAGIC S.PersonnelNumber,
# MAGIC S.ProfitabilitySegmentNumber,
# MAGIC S.OrderCategory,
# MAGIC S.WbsElement,
# MAGIC S.Project,
# MAGIC S.ServiceDocumentItemId,
# MAGIC S.ServiceContractItemId,
# MAGIC S.SolutionOrderItemId,
# MAGIC S.PartnerOrderCategory,
# MAGIC S.PartnerWbsElement,
# MAGIC S.PartnerProject,
# MAGIC S.PartnerSalesOrderItem,
# MAGIC S.PartnerProfitabilitySegmentNumber,
# MAGIC S.DocumentItemNumber,
# MAGIC S.DocumentNumber,
# MAGIC S.PostingRow,
# MAGIC S.PostingRowOfReferenceDocument,
# MAGIC S.ObjectIdOfTheResource,
# MAGIC S.OrderItemNumber,
# MAGIC S.PartnerOrderItemNumber,
# MAGIC S.PlannedPartsWork,
# MAGIC S.CcFiscalPeriodForBudgetConsumptionDate,
# MAGIC S.CcFiscalYearForBudgetConsumptionDate,
# MAGIC S.EarmarkedFundsDocumentItem,
# MAGIC S.CutbackRunId,
# MAGIC S.FiscalPeriod,
# MAGIC S.TransactionCode,
# MAGIC S.RecurringEntryDocumentFiscalYear,
# MAGIC S.FiscalYearOfReversalDocument,
# MAGIC S.CurrencyKey,
# MAGIC S.ExchangeRate,
# MAGIC S.GroupCurrencyExchangeRate,
# MAGIC S.UnplannedDeliveryCosts,
# MAGIC S.BusinessTransaction,
# MAGIC S.ObjectKey,
# MAGIC S.LocalCurrency,
# MAGIC S.ExchangeRateForTaxes,
# MAGIC S.RateForTaxValuesInCountryCurrency,
# MAGIC S.TimeOfParking,
# MAGIC S.NumberOfPagesOfInvoice,
# MAGIC S.CashRelevantDocument,
# MAGIC S.ExchangeRateType,
# MAGIC S.MarketDataExchangeRate,
# MAGIC S.FiscYearOfAnAccDocInTheSenderSystem,
# MAGIC S.InternallyAssignedSubidForAwkey,
# MAGIC S.AnnexationAmount,
# MAGIC S.AnnexationPercentage,
# MAGIC S.LastChangedAt,
# MAGIC S.DataSource,
# MAGIC now()
# MAGIC )

# COMMAND ----------

if(ts_acdoca != None):
    spark.sql ("update config.INCR_DataLoadTracking set LastUpdatedOn = '{0}' where SourceLayer = 'Transform' and SourceLayerTableName = 'ACDOCA' and DatabaseName = 'S42'".format(ts_acdoca))

if(ts_bkpf != None):
    spark.sql ("update config.INCR_DataLoadTracking set LastUpdatedOn = '{0}' where SourceLayer = 'Transform' and SourceLayerTableName = 'BKPF' and DatabaseName = 'S42'".format(ts_bkpf))

# COMMAND ----------

df_sf = spark.sql("select * from FEDW.accounting where UpdatedOn > (select LastUpdatedOn from config.INCR_DataLoadTracking where SourceLayer = 'Consumption' and SourceLayerTableName = 'Accounting' and DatabaseName = 'FEDW' )")
ts_sf = df_sf.agg({"UpdatedOn": "max"}).collect()[0]
ts_po_receipts = ts_sf["max(UpdatedOn)"]
print(ts_po_receipts)

# COMMAND ----------

sfUrl = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfUrl'").first()[0]
sfUser = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfUser'").first()[0]
sfPassword = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfPassword'").first()[0]
sfDatabase = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfDatabase'").first()[0]
sfSchema = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfSchema'").first()[0]
sfWarehouse = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfWarehouse'").first()[0]
sfRole = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfRole'").first()[0]
insecureMode = spark.sql("select variable_value from Config.config_constant where variable_name = 'insecureMode'").first()[0]

options = {
  "sfUrl": sfUrl,
  "sfUser": sfUser,
  "sfPassword": sfPassword,
  "sfDatabase": sfDatabase,
  "sfSchema": sfSchema,
  "sfWarehouse": sfWarehouse,
  "sfRole": sfRole,
  "insecureMode": insecureMode
}

# COMMAND ----------

df_sf.write \
  .format("net.snowflake.spark.snowflake") \
  .options(**options) \
  .option("dbtable", "Accounting") \
  .mode("OVERWRITE") \
  .save()

# COMMAND ----------

# MAGIC %scala
# MAGIC 
# MAGIC import org.apache.spark.sql._
# MAGIC 
# MAGIC val sfUrl = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfUrl'").first().getString(0)
# MAGIC val sfUser = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfUser'").first().getString(0)
# MAGIC val sfPassword = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfPassword'").first().getString(0)
# MAGIC val sfDatabase = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfDatabase'").first().getString(0)
# MAGIC val sfSchema = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfSchema'").first().getString(0)
# MAGIC val sfWarehouse = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfWarehouse'").first().getString(0)
# MAGIC val sfRole = spark.sql("select variable_value from Config.config_constant where variable_name = 'sfRole'").first().getString(0)
# MAGIC val insecureMode = spark.sql("select variable_value from Config.config_constant where variable_name = 'insecureMode'").first().getString(0)
# MAGIC 
# MAGIC 
# MAGIC val options = Map(
# MAGIC   "sfUrl" -> sfUrl,
# MAGIC   "sfUser" -> sfUser,
# MAGIC   "sfPassword" -> sfPassword,
# MAGIC   "sfDatabase" -> sfDatabase,
# MAGIC   "sfSchema" -> sfSchema,
# MAGIC   "sfWarehouse" -> sfWarehouse,
# MAGIC   "sfRole" -> sfRole,
# MAGIC    "insecureMode" -> insecureMode
# MAGIC )
# MAGIC 
# MAGIC import net.snowflake.spark.snowflake.Utils
# MAGIC  
# MAGIC Utils.runQuery(options, """call sp_load_accounting()""")

# COMMAND ----------

if(ts_po_receipts != None):
    spark.sql ("update INCR_DataLoadTracking set LastUpdatedOn = '{0}' where SourceLayer = 'Consumption' and SourceLayerTableName = 'PO_Receipts' and DatabaseName = 'FEDW'".format(ts_po_receipts))

# COMMAND ----------


